networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  bot:
    image: ghcr.io/njfamirm/dcd-bot:latest

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:
      alwatr-public-network:

    depends_on:
      - storage-api

    environment:
      - STORAGE_HOST=${appId}-storage-api
      - STORAGE_PORT=80
      - STORAGE_TOKEN=${storageAccessToken}
      - ALWATR_DEBUG=${apiDebug:-}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${domain}; PathPrefix:/api/v1/;
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
