networks:
  internal:

services:
  bot:
    image: ghcr.io/njfamirm/dcd-bot:latest

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:

    environment:
      - DEBUG=${botDebug:-}
      - botAdminChatId=${botAdminChatId}
      - botToken=${botToken}
      - botUsername=${botUsername}

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'
